name: Vanilla Desktop Nvidia Experimental
id: nvidia-exp
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  - name: nvidia-official-repo
    type: shell
    commands:
    - curl -fSsL https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/3bf863cc.pub | gpg --dearmor -o /usr/share/keyrings/nvidia-drivers.gpg
    - echo 'deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/ /' > /etc/apt/sources.list.d/nvidia-drivers.list
    - apt-get update

  - name: install-repacked-debs
    type: shell
    commands:
    - VERSION=575.57.08-1
    - mkdir -p /tmp/nvidia
    - cd /tmp/nvidia
    - wget https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/nvidia-driver-libs_${VERSION}_amd64.deb
    - dpkg-deb -x nvidia-driver-libs_${VERSION}_amd64.deb nvidia-driver-libs_${VERSION}_amd64
    - dpkg -e nvidia-driver-libs_${VERSION}_amd64.deb nvidia-driver-libs_${VERSION}_amd64/DEBIAN
    - rm nvidia-driver-libs_${VERSION}_amd64.deb 
    - sed -i "s/libnvidia-egl-xlib1 (<= ${VERSION}), libnvidia-egl-xlib1/libnvidia-egl-xlib1 (<= ${VERSION}) | libnvidia-egl-xlib1/g" nvidia-driver-libs_${VERSION}_amd64/DEBIAN/control
    - sed -i "s/libnvidia-egl-xcb1 (<= ${VERSION}), libnvidia-egl-xcb1/libnvidia-egl-xcb1 (<= ${VERSION}) | libnvidia-egl-xcb1/g" nvidia-driver-libs_${VERSION}_amd64/DEBIAN/control
    - dpkg-deb -b nvidia-driver-libs_${VERSION}_amd64 nvidia-driver-libs_${VERSION}_amd64.deb
    - apt update
    - apt install -y ./nvidia-driver-libs_575.51.03-1_amd64.deb
    - apt-mark hold nvidia-driver-libs
    - apt install -f

  - name: nvidia-official-driver
    type: shell
    commands:
    - apt-mark hold nvidia-kernel-open nvidia-driver nvidia-vaapi-driver nvidia-settings nvidia-persistenced nvidia-smi libnvidia-cfg1 libnvidia-glcore libnvidia-glvkspirv libnvidia-gpucomp libnvidia-fbc1 nvidia-container-toolkit
    modules:
      - name: install-nvidia
        type: apt
        source:
          packages:
          - nvidia-kernel-open
          - nvidia-driver
          - nvidia-vaapi-driver
          - nvidia-settings
          - nvidia-persistenced
          - cuda-drivers
          - libnvidia-cfg1
          - libnvidia-glcore
          - libnvidia-glvkspirv
          - libnvidia-gpucomp
          - libnvidia-fbc1
          - nvidia-container-toolkit

  - name: nvidia-sysd-units
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/systemd-suspend.service.wants
    - mkdir -p /etc/systemd/system/systemd-hibernate.service.wants
    - ln -s /usr/lib/systemd/system/nvidia-suspend.service /etc/systemd/system/systemd-suspend.service.wants/nvidia-suspend.service
    - ln -s /usr/lib/systemd/system/nvidia-hibernate.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-hibernate.service
    - ln -s /usr/lib/systemd/system/nvidia-resume.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-resume.service

  - name: extra-utilities
    type: apt
    source:
      packages:
      - switcheroo-control

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
      checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/nrun /usr/bin/nrun
    - cp /sources/vanilla-tools/vanilla-tools/prime-switch /usr/bin/prime-switch
    - chmod +x /usr/bin/nrun
    - chmod +x /usr/bin/prime-switch

  - name: enable-wayland
    type: shell
    commands:
    - mkdir -p /etc/udev/rules.d
    - ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - apt remove -y zutty gnome-shell-extension-prefs
    - SUDO_FORCE_REMOVE=yes apt purge -y sudo
    - lpkg --lock
    - rm /etc/apt/sources.list.d/nvidia-drivers.list 

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
