name: Vanilla Desktop Nvidia Experimental
id: nvidia-exp
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  - name: packages-modules
    type: includes
    includes:
      - modules/50-nvidia-driver-install.yml
      - modules/51-nvidia-systemd-units.yml

  - name: extra-utilities
    type: apt
    source:
      packages:
      - switcheroo-control

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
      checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/nrun /usr/bin/nrun
    - cp /sources/vanilla-tools/vanilla-tools/prime-switch /usr/bin/prime-switch
    - chmod +x /usr/bin/nrun
    - chmod +x /usr/bin/prime-switch

  - name: enable-wayland
    type: shell
    commands:
      - mkdir -p /etc/udev/rules.d
      - ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

  - name: gnome-stuff
    type: apt 
    source:
      packages:
        - gnome-tweaks
        - podman-compose
				- libicu76

  - name: pipewire-additionals
    type: apt
    source:
      packages:
        - libpipewire-0.3-0t64
        - libpipewire-0.3-common
        - libpipewire-0.3-modules
        - pipewire
        - pipewire-alsa
        - pipewire-bin
        - pipewire-jack
        - pipewire-pulse
        - libwireplumber-0.5-0

  - name: fuse-dependencies
    type: apt
    source:
      packages:
        - fuse
        - fuse2fs
        - fuse3
        - libfuse2t64
        - libfuse3-4
        - mesa-utils

  - name: adguard-cli
    type: shell
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - export USER=root
      - export HOME=/root
      - apt-get update
      - apt-get install -y curl ca-certificates
      - curl -fsSL -o /tmp/install.sh https://raw.githubusercontent.com/AdguardTeam/AdGuardCLI/release/adguard-cli.sh
      - chmod +x /tmp/adguard-cli.sh
      - /bin/sh /tmp/adguard-cli.sh -v || true
      - mkdir -p /usr/local/bin
      - ln -sf /opt/adguardcli/adguard-cli /usr/local/bin/adguard-cli

  - name: adguardvpn-cli
    type: shell
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - export USER=root
      - export HOME=/root
      - apt-get update
      - apt-get install -y curl ca-certificates
      - curl -fsSL https://raw.githubusercontent.com/AdguardTeam/AdGuardVPNCLI/HEAD/scripts/release/install.sh -o /tmp/install.sh
      - chmod +x /tmp/install.sh
      - /bin/sh /tmp/install.sh -v || true
      - mkdir -p /usr/local/bin
      - ln -sf /opt/adguardvpn_cli/adguardvpn-cli /usr/local/bin/adguardvpn-cli
      - /usr/local/bin/adguardvpn-cli -v

  - name: cleanup
    type: shell
    commands:
      - apt autoremove -y
      - apt clean
      - apt remove -y zutty gnome-shell-extension-prefs
      - SUDO_FORCE_REMOVE=yes apt purge -y sudo
      - lpkg --lock
      - rm /etc/apt/sources.list.d/nvidia-drivers.list 

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
